// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v2ray.com/core/proxy/blackhole/config.proto

package com.v2ray.core.proxy.blackhole;

public interface NoneResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:v2ray.core.proxy.blackhole.NoneResponse)
    com.google.protobuf.MessageOrBuilder {
}
