// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v2ray.com/core/common/serial/typed_message.proto

package com.v2ray.core.common.serial;

public final class TypedMessageOuterClass {
  private TypedMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v2ray_core_common_serial_TypedMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v2ray_core_common_serial_TypedMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n0v2ray.com/core/common/serial/typed_mes" +
      "sage.proto\022\030v2ray.core.common.serial\"+\n\014" +
      "TypedMessage\022\014\n\004type\030\001 \001(\t\022\r\n\005value\030\002 \001(" +
      "\014BC\n\034com.v2ray.core.common.serialP\001Z\006ser" +
      "ial\252\002\030V2Ray.Core.Common.Serialb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_v2ray_core_common_serial_TypedMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_v2ray_core_common_serial_TypedMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v2ray_core_common_serial_TypedMessage_descriptor,
        new String[] { "Type", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
