// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v2ray.com/core/app/log/command/config.proto

package com.v2ray.core.app.log.command;

public interface RestartLoggerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:v2ray.core.app.log.command.RestartLoggerResponse)
    com.google.protobuf.MessageOrBuilder {
}
