// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v2ray.com/core/transport/internet/headers/http/config.proto

package com.v2ray.core.transport.internet.headers.http;

/**
 * Protobuf type {@code v2ray.core.transport.internet.headers.http.RequestConfig}
 */
public  final class RequestConfig extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:v2ray.core.transport.internet.headers.http.RequestConfig)
    RequestConfigOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RequestConfig.newBuilder() to construct.
  private RequestConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RequestConfig() {
    uri_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    header_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RequestConfig(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            Version.Builder subBuilder = null;
            if (version_ != null) {
              subBuilder = version_.toBuilder();
            }
            version_ = input.readMessage(Version.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(version_);
              version_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            Method.Builder subBuilder = null;
            if (method_ != null) {
              subBuilder = method_.toBuilder();
            }
            method_ = input.readMessage(Method.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(method_);
              method_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000004) != 0)) {
              uri_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000004;
            }
            uri_.add(s);
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) != 0)) {
              header_ = new java.util.ArrayList<Header>();
              mutable_bitField0_ |= 0x00000008;
            }
            header_.add(
                input.readMessage(Header.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) != 0)) {
        uri_ = uri_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000008) != 0)) {
        header_ = java.util.Collections.unmodifiableList(header_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.v2ray.core.transport.internet.headers.http.ConfigOuterClass.internal_static_v2ray_core_transport_internet_headers_http_RequestConfig_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.v2ray.core.transport.internet.headers.http.ConfigOuterClass.internal_static_v2ray_core_transport_internet_headers_http_RequestConfig_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            RequestConfig.class, Builder.class);
  }

  private int bitField0_;
  public static final int VERSION_FIELD_NUMBER = 1;
  private Version version_;
  /**
   * <pre>
   * Full HTTP version like "1.1".
   * </pre>
   *
   * <code>.v2ray.core.transport.internet.headers.http.Version version = 1;</code>
   */
  public boolean hasVersion() {
    return version_ != null;
  }
  /**
   * <pre>
   * Full HTTP version like "1.1".
   * </pre>
   *
   * <code>.v2ray.core.transport.internet.headers.http.Version version = 1;</code>
   */
  public Version getVersion() {
    return version_ == null ? Version.getDefaultInstance() : version_;
  }
  /**
   * <pre>
   * Full HTTP version like "1.1".
   * </pre>
   *
   * <code>.v2ray.core.transport.internet.headers.http.Version version = 1;</code>
   */
  public com.v2ray.core.transport.internet.headers.http.VersionOrBuilder getVersionOrBuilder() {
    return getVersion();
  }

  public static final int METHOD_FIELD_NUMBER = 2;
  private Method method_;
  /**
   * <pre>
   * GET, POST, CONNECT etc
   * </pre>
   *
   * <code>.v2ray.core.transport.internet.headers.http.Method method = 2;</code>
   */
  public boolean hasMethod() {
    return method_ != null;
  }
  /**
   * <pre>
   * GET, POST, CONNECT etc
   * </pre>
   *
   * <code>.v2ray.core.transport.internet.headers.http.Method method = 2;</code>
   */
  public Method getMethod() {
    return method_ == null ? Method.getDefaultInstance() : method_;
  }
  /**
   * <pre>
   * GET, POST, CONNECT etc
   * </pre>
   *
   * <code>.v2ray.core.transport.internet.headers.http.Method method = 2;</code>
   */
  public com.v2ray.core.transport.internet.headers.http.MethodOrBuilder getMethodOrBuilder() {
    return getMethod();
  }

  public static final int URI_FIELD_NUMBER = 3;
  private com.google.protobuf.LazyStringList uri_;
  /**
   * <pre>
   * URI like "/login.php"
   * </pre>
   *
   * <code>repeated string uri = 3;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getUriList() {
    return uri_;
  }
  /**
   * <pre>
   * URI like "/login.php"
   * </pre>
   *
   * <code>repeated string uri = 3;</code>
   */
  public int getUriCount() {
    return uri_.size();
  }
  /**
   * <pre>
   * URI like "/login.php"
   * </pre>
   *
   * <code>repeated string uri = 3;</code>
   */
  public String getUri(int index) {
    return uri_.get(index);
  }
  /**
   * <pre>
   * URI like "/login.php"
   * </pre>
   *
   * <code>repeated string uri = 3;</code>
   */
  public com.google.protobuf.ByteString
      getUriBytes(int index) {
    return uri_.getByteString(index);
  }

  public static final int HEADER_FIELD_NUMBER = 4;
  private java.util.List<Header> header_;
  /**
   * <code>repeated .v2ray.core.transport.internet.headers.http.Header header = 4;</code>
   */
  public java.util.List<Header> getHeaderList() {
    return header_;
  }
  /**
   * <code>repeated .v2ray.core.transport.internet.headers.http.Header header = 4;</code>
   */
  public java.util.List<? extends com.v2ray.core.transport.internet.headers.http.HeaderOrBuilder> 
      getHeaderOrBuilderList() {
    return header_;
  }
  /**
   * <code>repeated .v2ray.core.transport.internet.headers.http.Header header = 4;</code>
   */
  public int getHeaderCount() {
    return header_.size();
  }
  /**
   * <code>repeated .v2ray.core.transport.internet.headers.http.Header header = 4;</code>
   */
  public Header getHeader(int index) {
    return header_.get(index);
  }
  /**
   * <code>repeated .v2ray.core.transport.internet.headers.http.Header header = 4;</code>
   */
  public com.v2ray.core.transport.internet.headers.http.HeaderOrBuilder getHeaderOrBuilder(
      int index) {
    return header_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (version_ != null) {
      output.writeMessage(1, getVersion());
    }
    if (method_ != null) {
      output.writeMessage(2, getMethod());
    }
    for (int i = 0; i < uri_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, uri_.getRaw(i));
    }
    for (int i = 0; i < header_.size(); i++) {
      output.writeMessage(4, header_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (version_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getVersion());
    }
    if (method_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getMethod());
    }
    {
      int dataSize = 0;
      for (int i = 0; i < uri_.size(); i++) {
        dataSize += computeStringSizeNoTag(uri_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getUriList().size();
    }
    for (int i = 0; i < header_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, header_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof RequestConfig)) {
      return super.equals(obj);
    }
    RequestConfig other = (RequestConfig) obj;

    if (hasVersion() != other.hasVersion()) return false;
    if (hasVersion()) {
      if (!getVersion()
          .equals(other.getVersion())) return false;
    }
    if (hasMethod() != other.hasMethod()) return false;
    if (hasMethod()) {
      if (!getMethod()
          .equals(other.getMethod())) return false;
    }
    if (!getUriList()
        .equals(other.getUriList())) return false;
    if (!getHeaderList()
        .equals(other.getHeaderList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasVersion()) {
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
    }
    if (hasMethod()) {
      hash = (37 * hash) + METHOD_FIELD_NUMBER;
      hash = (53 * hash) + getMethod().hashCode();
    }
    if (getUriCount() > 0) {
      hash = (37 * hash) + URI_FIELD_NUMBER;
      hash = (53 * hash) + getUriList().hashCode();
    }
    if (getHeaderCount() > 0) {
      hash = (37 * hash) + HEADER_FIELD_NUMBER;
      hash = (53 * hash) + getHeaderList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static RequestConfig parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RequestConfig parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RequestConfig parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RequestConfig parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RequestConfig parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RequestConfig parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RequestConfig parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static RequestConfig parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static RequestConfig parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static RequestConfig parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static RequestConfig parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static RequestConfig parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(RequestConfig prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code v2ray.core.transport.internet.headers.http.RequestConfig}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:v2ray.core.transport.internet.headers.http.RequestConfig)
      com.v2ray.core.transport.internet.headers.http.RequestConfigOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.v2ray.core.transport.internet.headers.http.ConfigOuterClass.internal_static_v2ray_core_transport_internet_headers_http_RequestConfig_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.v2ray.core.transport.internet.headers.http.ConfigOuterClass.internal_static_v2ray_core_transport_internet_headers_http_RequestConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RequestConfig.class, Builder.class);
    }

    // Construct using com.v2ray.core.transport.internet.headers.http.RequestConfig.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getHeaderFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      if (versionBuilder_ == null) {
        version_ = null;
      } else {
        version_ = null;
        versionBuilder_ = null;
      }
      if (methodBuilder_ == null) {
        method_ = null;
      } else {
        method_ = null;
        methodBuilder_ = null;
      }
      uri_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      if (headerBuilder_ == null) {
        header_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        headerBuilder_.clear();
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.v2ray.core.transport.internet.headers.http.ConfigOuterClass.internal_static_v2ray_core_transport_internet_headers_http_RequestConfig_descriptor;
    }

    @Override
    public RequestConfig getDefaultInstanceForType() {
      return RequestConfig.getDefaultInstance();
    }

    @Override
    public RequestConfig build() {
      RequestConfig result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public RequestConfig buildPartial() {
      RequestConfig result = new RequestConfig(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (versionBuilder_ == null) {
        result.version_ = version_;
      } else {
        result.version_ = versionBuilder_.build();
      }
      if (methodBuilder_ == null) {
        result.method_ = method_;
      } else {
        result.method_ = methodBuilder_.build();
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        uri_ = uri_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.uri_ = uri_;
      if (headerBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          header_ = java.util.Collections.unmodifiableList(header_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.header_ = header_;
      } else {
        result.header_ = headerBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof RequestConfig) {
        return mergeFrom((RequestConfig)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(RequestConfig other) {
      if (other == RequestConfig.getDefaultInstance()) return this;
      if (other.hasVersion()) {
        mergeVersion(other.getVersion());
      }
      if (other.hasMethod()) {
        mergeMethod(other.getMethod());
      }
      if (!other.uri_.isEmpty()) {
        if (uri_.isEmpty()) {
          uri_ = other.uri_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureUriIsMutable();
          uri_.addAll(other.uri_);
        }
        onChanged();
      }
      if (headerBuilder_ == null) {
        if (!other.header_.isEmpty()) {
          if (header_.isEmpty()) {
            header_ = other.header_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureHeaderIsMutable();
            header_.addAll(other.header_);
          }
          onChanged();
        }
      } else {
        if (!other.header_.isEmpty()) {
          if (headerBuilder_.isEmpty()) {
            headerBuilder_.dispose();
            headerBuilder_ = null;
            header_ = other.header_;
            bitField0_ = (bitField0_ & ~0x00000008);
            headerBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getHeaderFieldBuilder() : null;
          } else {
            headerBuilder_.addAllMessages(other.header_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      RequestConfig parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (RequestConfig) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private Version version_;
    private com.google.protobuf.SingleFieldBuilderV3<
        Version, Version.Builder, com.v2ray.core.transport.internet.headers.http.VersionOrBuilder> versionBuilder_;
    /**
     * <pre>
     * Full HTTP version like "1.1".
     * </pre>
     *
     * <code>.v2ray.core.transport.internet.headers.http.Version version = 1;</code>
     */
    public boolean hasVersion() {
      return versionBuilder_ != null || version_ != null;
    }
    /**
     * <pre>
     * Full HTTP version like "1.1".
     * </pre>
     *
     * <code>.v2ray.core.transport.internet.headers.http.Version version = 1;</code>
     */
    public Version getVersion() {
      if (versionBuilder_ == null) {
        return version_ == null ? Version.getDefaultInstance() : version_;
      } else {
        return versionBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Full HTTP version like "1.1".
     * </pre>
     *
     * <code>.v2ray.core.transport.internet.headers.http.Version version = 1;</code>
     */
    public Builder setVersion(Version value) {
      if (versionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        version_ = value;
        onChanged();
      } else {
        versionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Full HTTP version like "1.1".
     * </pre>
     *
     * <code>.v2ray.core.transport.internet.headers.http.Version version = 1;</code>
     */
    public Builder setVersion(
        Version.Builder builderForValue) {
      if (versionBuilder_ == null) {
        version_ = builderForValue.build();
        onChanged();
      } else {
        versionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Full HTTP version like "1.1".
     * </pre>
     *
     * <code>.v2ray.core.transport.internet.headers.http.Version version = 1;</code>
     */
    public Builder mergeVersion(Version value) {
      if (versionBuilder_ == null) {
        if (version_ != null) {
          version_ =
            Version.newBuilder(version_).mergeFrom(value).buildPartial();
        } else {
          version_ = value;
        }
        onChanged();
      } else {
        versionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Full HTTP version like "1.1".
     * </pre>
     *
     * <code>.v2ray.core.transport.internet.headers.http.Version version = 1;</code>
     */
    public Builder clearVersion() {
      if (versionBuilder_ == null) {
        version_ = null;
        onChanged();
      } else {
        version_ = null;
        versionBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Full HTTP version like "1.1".
     * </pre>
     *
     * <code>.v2ray.core.transport.internet.headers.http.Version version = 1;</code>
     */
    public Version.Builder getVersionBuilder() {
      
      onChanged();
      return getVersionFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Full HTTP version like "1.1".
     * </pre>
     *
     * <code>.v2ray.core.transport.internet.headers.http.Version version = 1;</code>
     */
    public com.v2ray.core.transport.internet.headers.http.VersionOrBuilder getVersionOrBuilder() {
      if (versionBuilder_ != null) {
        return versionBuilder_.getMessageOrBuilder();
      } else {
        return version_ == null ?
            Version.getDefaultInstance() : version_;
      }
    }
    /**
     * <pre>
     * Full HTTP version like "1.1".
     * </pre>
     *
     * <code>.v2ray.core.transport.internet.headers.http.Version version = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Version, Version.Builder, com.v2ray.core.transport.internet.headers.http.VersionOrBuilder>
        getVersionFieldBuilder() {
      if (versionBuilder_ == null) {
        versionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Version, Version.Builder, com.v2ray.core.transport.internet.headers.http.VersionOrBuilder>(
                getVersion(),
                getParentForChildren(),
                isClean());
        version_ = null;
      }
      return versionBuilder_;
    }

    private Method method_;
    private com.google.protobuf.SingleFieldBuilderV3<
        Method, Method.Builder, com.v2ray.core.transport.internet.headers.http.MethodOrBuilder> methodBuilder_;
    /**
     * <pre>
     * GET, POST, CONNECT etc
     * </pre>
     *
     * <code>.v2ray.core.transport.internet.headers.http.Method method = 2;</code>
     */
    public boolean hasMethod() {
      return methodBuilder_ != null || method_ != null;
    }
    /**
     * <pre>
     * GET, POST, CONNECT etc
     * </pre>
     *
     * <code>.v2ray.core.transport.internet.headers.http.Method method = 2;</code>
     */
    public Method getMethod() {
      if (methodBuilder_ == null) {
        return method_ == null ? Method.getDefaultInstance() : method_;
      } else {
        return methodBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * GET, POST, CONNECT etc
     * </pre>
     *
     * <code>.v2ray.core.transport.internet.headers.http.Method method = 2;</code>
     */
    public Builder setMethod(Method value) {
      if (methodBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        method_ = value;
        onChanged();
      } else {
        methodBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * GET, POST, CONNECT etc
     * </pre>
     *
     * <code>.v2ray.core.transport.internet.headers.http.Method method = 2;</code>
     */
    public Builder setMethod(
        Method.Builder builderForValue) {
      if (methodBuilder_ == null) {
        method_ = builderForValue.build();
        onChanged();
      } else {
        methodBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * GET, POST, CONNECT etc
     * </pre>
     *
     * <code>.v2ray.core.transport.internet.headers.http.Method method = 2;</code>
     */
    public Builder mergeMethod(Method value) {
      if (methodBuilder_ == null) {
        if (method_ != null) {
          method_ =
            Method.newBuilder(method_).mergeFrom(value).buildPartial();
        } else {
          method_ = value;
        }
        onChanged();
      } else {
        methodBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * GET, POST, CONNECT etc
     * </pre>
     *
     * <code>.v2ray.core.transport.internet.headers.http.Method method = 2;</code>
     */
    public Builder clearMethod() {
      if (methodBuilder_ == null) {
        method_ = null;
        onChanged();
      } else {
        method_ = null;
        methodBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * GET, POST, CONNECT etc
     * </pre>
     *
     * <code>.v2ray.core.transport.internet.headers.http.Method method = 2;</code>
     */
    public Method.Builder getMethodBuilder() {
      
      onChanged();
      return getMethodFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * GET, POST, CONNECT etc
     * </pre>
     *
     * <code>.v2ray.core.transport.internet.headers.http.Method method = 2;</code>
     */
    public com.v2ray.core.transport.internet.headers.http.MethodOrBuilder getMethodOrBuilder() {
      if (methodBuilder_ != null) {
        return methodBuilder_.getMessageOrBuilder();
      } else {
        return method_ == null ?
            Method.getDefaultInstance() : method_;
      }
    }
    /**
     * <pre>
     * GET, POST, CONNECT etc
     * </pre>
     *
     * <code>.v2ray.core.transport.internet.headers.http.Method method = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Method, Method.Builder, com.v2ray.core.transport.internet.headers.http.MethodOrBuilder>
        getMethodFieldBuilder() {
      if (methodBuilder_ == null) {
        methodBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Method, Method.Builder, com.v2ray.core.transport.internet.headers.http.MethodOrBuilder>(
                getMethod(),
                getParentForChildren(),
                isClean());
        method_ = null;
      }
      return methodBuilder_;
    }

    private com.google.protobuf.LazyStringList uri_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureUriIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        uri_ = new com.google.protobuf.LazyStringArrayList(uri_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <pre>
     * URI like "/login.php"
     * </pre>
     *
     * <code>repeated string uri = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getUriList() {
      return uri_.getUnmodifiableView();
    }
    /**
     * <pre>
     * URI like "/login.php"
     * </pre>
     *
     * <code>repeated string uri = 3;</code>
     */
    public int getUriCount() {
      return uri_.size();
    }
    /**
     * <pre>
     * URI like "/login.php"
     * </pre>
     *
     * <code>repeated string uri = 3;</code>
     */
    public String getUri(int index) {
      return uri_.get(index);
    }
    /**
     * <pre>
     * URI like "/login.php"
     * </pre>
     *
     * <code>repeated string uri = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUriBytes(int index) {
      return uri_.getByteString(index);
    }
    /**
     * <pre>
     * URI like "/login.php"
     * </pre>
     *
     * <code>repeated string uri = 3;</code>
     */
    public Builder setUri(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureUriIsMutable();
      uri_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * URI like "/login.php"
     * </pre>
     *
     * <code>repeated string uri = 3;</code>
     */
    public Builder addUri(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureUriIsMutable();
      uri_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * URI like "/login.php"
     * </pre>
     *
     * <code>repeated string uri = 3;</code>
     */
    public Builder addAllUri(
        Iterable<String> values) {
      ensureUriIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, uri_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * URI like "/login.php"
     * </pre>
     *
     * <code>repeated string uri = 3;</code>
     */
    public Builder clearUri() {
      uri_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * URI like "/login.php"
     * </pre>
     *
     * <code>repeated string uri = 3;</code>
     */
    public Builder addUriBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureUriIsMutable();
      uri_.add(value);
      onChanged();
      return this;
    }

    private java.util.List<Header> header_ =
      java.util.Collections.emptyList();
    private void ensureHeaderIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        header_ = new java.util.ArrayList<Header>(header_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        Header, Header.Builder, com.v2ray.core.transport.internet.headers.http.HeaderOrBuilder> headerBuilder_;

    /**
     * <code>repeated .v2ray.core.transport.internet.headers.http.Header header = 4;</code>
     */
    public java.util.List<Header> getHeaderList() {
      if (headerBuilder_ == null) {
        return java.util.Collections.unmodifiableList(header_);
      } else {
        return headerBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .v2ray.core.transport.internet.headers.http.Header header = 4;</code>
     */
    public int getHeaderCount() {
      if (headerBuilder_ == null) {
        return header_.size();
      } else {
        return headerBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .v2ray.core.transport.internet.headers.http.Header header = 4;</code>
     */
    public Header getHeader(int index) {
      if (headerBuilder_ == null) {
        return header_.get(index);
      } else {
        return headerBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .v2ray.core.transport.internet.headers.http.Header header = 4;</code>
     */
    public Builder setHeader(
        int index, Header value) {
      if (headerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHeaderIsMutable();
        header_.set(index, value);
        onChanged();
      } else {
        headerBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .v2ray.core.transport.internet.headers.http.Header header = 4;</code>
     */
    public Builder setHeader(
        int index, Header.Builder builderForValue) {
      if (headerBuilder_ == null) {
        ensureHeaderIsMutable();
        header_.set(index, builderForValue.build());
        onChanged();
      } else {
        headerBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .v2ray.core.transport.internet.headers.http.Header header = 4;</code>
     */
    public Builder addHeader(Header value) {
      if (headerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHeaderIsMutable();
        header_.add(value);
        onChanged();
      } else {
        headerBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .v2ray.core.transport.internet.headers.http.Header header = 4;</code>
     */
    public Builder addHeader(
        int index, Header value) {
      if (headerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHeaderIsMutable();
        header_.add(index, value);
        onChanged();
      } else {
        headerBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .v2ray.core.transport.internet.headers.http.Header header = 4;</code>
     */
    public Builder addHeader(
        Header.Builder builderForValue) {
      if (headerBuilder_ == null) {
        ensureHeaderIsMutable();
        header_.add(builderForValue.build());
        onChanged();
      } else {
        headerBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .v2ray.core.transport.internet.headers.http.Header header = 4;</code>
     */
    public Builder addHeader(
        int index, Header.Builder builderForValue) {
      if (headerBuilder_ == null) {
        ensureHeaderIsMutable();
        header_.add(index, builderForValue.build());
        onChanged();
      } else {
        headerBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .v2ray.core.transport.internet.headers.http.Header header = 4;</code>
     */
    public Builder addAllHeader(
        Iterable<? extends Header> values) {
      if (headerBuilder_ == null) {
        ensureHeaderIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, header_);
        onChanged();
      } else {
        headerBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .v2ray.core.transport.internet.headers.http.Header header = 4;</code>
     */
    public Builder clearHeader() {
      if (headerBuilder_ == null) {
        header_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        headerBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .v2ray.core.transport.internet.headers.http.Header header = 4;</code>
     */
    public Builder removeHeader(int index) {
      if (headerBuilder_ == null) {
        ensureHeaderIsMutable();
        header_.remove(index);
        onChanged();
      } else {
        headerBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .v2ray.core.transport.internet.headers.http.Header header = 4;</code>
     */
    public Header.Builder getHeaderBuilder(
        int index) {
      return getHeaderFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .v2ray.core.transport.internet.headers.http.Header header = 4;</code>
     */
    public com.v2ray.core.transport.internet.headers.http.HeaderOrBuilder getHeaderOrBuilder(
        int index) {
      if (headerBuilder_ == null) {
        return header_.get(index);  } else {
        return headerBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .v2ray.core.transport.internet.headers.http.Header header = 4;</code>
     */
    public java.util.List<? extends com.v2ray.core.transport.internet.headers.http.HeaderOrBuilder> 
         getHeaderOrBuilderList() {
      if (headerBuilder_ != null) {
        return headerBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(header_);
      }
    }
    /**
     * <code>repeated .v2ray.core.transport.internet.headers.http.Header header = 4;</code>
     */
    public Header.Builder addHeaderBuilder() {
      return getHeaderFieldBuilder().addBuilder(
          Header.getDefaultInstance());
    }
    /**
     * <code>repeated .v2ray.core.transport.internet.headers.http.Header header = 4;</code>
     */
    public Header.Builder addHeaderBuilder(
        int index) {
      return getHeaderFieldBuilder().addBuilder(
          index, Header.getDefaultInstance());
    }
    /**
     * <code>repeated .v2ray.core.transport.internet.headers.http.Header header = 4;</code>
     */
    public java.util.List<Header.Builder>
         getHeaderBuilderList() {
      return getHeaderFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        Header, Header.Builder, com.v2ray.core.transport.internet.headers.http.HeaderOrBuilder>
        getHeaderFieldBuilder() {
      if (headerBuilder_ == null) {
        headerBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            Header, Header.Builder, com.v2ray.core.transport.internet.headers.http.HeaderOrBuilder>(
                header_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        header_ = null;
      }
      return headerBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:v2ray.core.transport.internet.headers.http.RequestConfig)
  }

  // @@protoc_insertion_point(class_scope:v2ray.core.transport.internet.headers.http.RequestConfig)
  private static final RequestConfig DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new RequestConfig();
  }

  public static RequestConfig getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RequestConfig>
      PARSER = new com.google.protobuf.AbstractParser<RequestConfig>() {
    @Override
    public RequestConfig parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RequestConfig(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RequestConfig> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<RequestConfig> getParserForType() {
    return PARSER;
  }

  @Override
  public RequestConfig getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

