// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v2ray.com/core/transport/internet/headers/http/config.proto

package com.v2ray.core.transport.internet.headers.http;

public interface StatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:v2ray.core.transport.internet.headers.http.Status)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Status code. Default "200".
   * </pre>
   *
   * <code>string code = 1;</code>
   */
  String getCode();
  /**
   * <pre>
   * Status code. Default "200".
   * </pre>
   *
   * <code>string code = 1;</code>
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <pre>
   * Statue reason. Default "OK".
   * </pre>
   *
   * <code>string reason = 2;</code>
   */
  String getReason();
  /**
   * <pre>
   * Statue reason. Default "OK".
   * </pre>
   *
   * <code>string reason = 2;</code>
   */
  com.google.protobuf.ByteString
      getReasonBytes();
}
