// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v2ray.com/core/app/policy/config.proto

package com.v2ray.core.app.policy;

/**
 * Protobuf type {@code v2ray.core.app.policy.SystemPolicy}
 */
public final class SystemPolicy extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:v2ray.core.app.policy.SystemPolicy)
        SystemPolicyOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use SystemPolicy.newBuilder() to construct.
    private SystemPolicy(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private SystemPolicy() {
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    private SystemPolicy(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 10: {
                        Stats.Builder subBuilder = null;
                        if (stats_ != null) {
                            subBuilder = stats_.toBuilder();
                        }
                        stats_ = input.readMessage(Stats.parser(), extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom(stats_);
                            stats_ = subBuilder.buildPartial();
                        }

                        break;
                    }
                    default: {
                        if (!parseUnknownField(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return com.v2ray.core.app.policy.ConfigOuterClass.internal_static_v2ray_core_app_policy_SystemPolicy_descriptor;
    }

    @Override
    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
        return com.v2ray.core.app.policy.ConfigOuterClass.internal_static_v2ray_core_app_policy_SystemPolicy_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        SystemPolicy.class, Builder.class);
    }

    public interface StatsOrBuilder extends
            // @@protoc_insertion_point(interface_extends:v2ray.core.app.policy.SystemPolicy.Stats)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>bool inbound_uplink = 1;</code>
         */
        boolean getInboundUplink();

        /**
         * <code>bool inbound_downlink = 2;</code>
         */
        boolean getInboundDownlink();
    }

    /**
     * Protobuf type {@code v2ray.core.app.policy.SystemPolicy.Stats}
     */
    public static final class Stats extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:v2ray.core.app.policy.SystemPolicy.Stats)
            StatsOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use Stats.newBuilder() to construct.
        private Stats(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Stats() {
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private Stats(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            inboundUplink_ = input.readBool();
                            break;
                        }
                        case 16: {

                            inboundDownlink_ = input.readBool();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.v2ray.core.app.policy.ConfigOuterClass.internal_static_v2ray_core_app_policy_SystemPolicy_Stats_descriptor;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.v2ray.core.app.policy.ConfigOuterClass.internal_static_v2ray_core_app_policy_SystemPolicy_Stats_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Stats.class, Builder.class);
        }

        public static final int INBOUND_UPLINK_FIELD_NUMBER = 1;
        private boolean inboundUplink_;

        /**
         * <code>bool inbound_uplink = 1;</code>
         */
        public boolean getInboundUplink() {
            return inboundUplink_;
        }

        public static final int INBOUND_DOWNLINK_FIELD_NUMBER = 2;
        private boolean inboundDownlink_;

        /**
         * <code>bool inbound_downlink = 2;</code>
         */
        public boolean getInboundDownlink() {
            return inboundDownlink_;
        }

        private byte memoizedIsInitialized = -1;

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (inboundUplink_ != false) {
                output.writeBool(1, inboundUplink_);
            }
            if (inboundDownlink_ != false) {
                output.writeBool(2, inboundDownlink_);
            }
            unknownFields.writeTo(output);
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (inboundUplink_ != false) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(1, inboundUplink_);
            }
            if (inboundDownlink_ != false) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(2, inboundDownlink_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Stats)) {
                return super.equals(obj);
            }
            Stats other = (Stats) obj;

            if (getInboundUplink()
                    != other.getInboundUplink()) return false;
            if (getInboundDownlink()
                    != other.getInboundDownlink()) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + INBOUND_UPLINK_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                    getInboundUplink());
            hash = (37 * hash) + INBOUND_DOWNLINK_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                    getInboundDownlink());
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static Stats parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Stats parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Stats parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Stats parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Stats parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Stats parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Stats parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static Stats parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Stats parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static Stats parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static Stats parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static Stats parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(Stats prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code v2ray.core.app.policy.SystemPolicy.Stats}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:v2ray.core.app.policy.SystemPolicy.Stats)
                StatsOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.v2ray.core.app.policy.ConfigOuterClass.internal_static_v2ray_core_app_policy_SystemPolicy_Stats_descriptor;
            }

            @Override
            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.v2ray.core.app.policy.ConfigOuterClass.internal_static_v2ray_core_app_policy_SystemPolicy_Stats_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Stats.class, Builder.class);
            }

            // Construct using com.v2ray.core.app.policy.SystemPolicy.Stats.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @Override
            public Builder clear() {
                super.clear();
                inboundUplink_ = false;

                inboundDownlink_ = false;

                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.v2ray.core.app.policy.ConfigOuterClass.internal_static_v2ray_core_app_policy_SystemPolicy_Stats_descriptor;
            }

            @Override
            public Stats getDefaultInstanceForType() {
                return Stats.getDefaultInstance();
            }

            @Override
            public Stats build() {
                Stats result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public Stats buildPartial() {
                Stats result = new Stats(this);
                result.inboundUplink_ = inboundUplink_;
                result.inboundDownlink_ = inboundDownlink_;
                onBuilt();
                return result;
            }

            @Override
            public Builder clone() {
                return super.clone();
            }

            @Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.setField(field, value);
            }

            @Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.addRepeatedField(field, value);
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Stats) {
                    return mergeFrom((Stats) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Stats other) {
                if (other == Stats.getDefaultInstance()) return this;
                if (other.getInboundUplink() != false) {
                    setInboundUplink(other.getInboundUplink());
                }
                if (other.getInboundDownlink() != false) {
                    setInboundDownlink(other.getInboundDownlink());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Stats parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Stats) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private boolean inboundUplink_;

            /**
             * <code>bool inbound_uplink = 1;</code>
             */
            public boolean getInboundUplink() {
                return inboundUplink_;
            }

            /**
             * <code>bool inbound_uplink = 1;</code>
             */
            public Builder setInboundUplink(boolean value) {

                inboundUplink_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>bool inbound_uplink = 1;</code>
             */
            public Builder clearInboundUplink() {

                inboundUplink_ = false;
                onChanged();
                return this;
            }

            private boolean inboundDownlink_;

            /**
             * <code>bool inbound_downlink = 2;</code>
             */
            public boolean getInboundDownlink() {
                return inboundDownlink_;
            }

            /**
             * <code>bool inbound_downlink = 2;</code>
             */
            public Builder setInboundDownlink(boolean value) {

                inboundDownlink_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>bool inbound_downlink = 2;</code>
             */
            public Builder clearInboundDownlink() {

                inboundDownlink_ = false;
                onChanged();
                return this;
            }

            @Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:v2ray.core.app.policy.SystemPolicy.Stats)
        }

        // @@protoc_insertion_point(class_scope:v2ray.core.app.policy.SystemPolicy.Stats)
        private static final Stats DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new Stats();
        }

        public static Stats getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Stats>
                PARSER = new com.google.protobuf.AbstractParser<Stats>() {
            @Override
            public Stats parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Stats(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Stats> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<Stats> getParserForType() {
            return PARSER;
        }

        @Override
        public Stats getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public static final int STATS_FIELD_NUMBER = 1;
    private Stats stats_;

    /**
     * <code>.v2ray.core.app.policy.SystemPolicy.Stats stats = 1;</code>
     */
    public boolean hasStats() {
        return stats_ != null;
    }

    /**
     * <code>.v2ray.core.app.policy.SystemPolicy.Stats stats = 1;</code>
     */
    public Stats getStats() {
        return stats_ == null ? Stats.getDefaultInstance() : stats_;
    }

    /**
     * <code>.v2ray.core.app.policy.SystemPolicy.Stats stats = 1;</code>
     */
    public StatsOrBuilder getStatsOrBuilder() {
        return getStats();
    }

    private byte memoizedIsInitialized = -1;

    @Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (stats_ != null) {
            output.writeMessage(1, getStats());
        }
        unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (stats_ != null) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(1, getStats());
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof SystemPolicy)) {
            return super.equals(obj);
        }
        SystemPolicy other = (SystemPolicy) obj;

        if (hasStats() != other.hasStats()) return false;
        if (hasStats()) {
            if (!getStats()
                    .equals(other.getStats())) return false;
        }
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasStats()) {
            hash = (37 * hash) + STATS_FIELD_NUMBER;
            hash = (53 * hash) + getStats().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static SystemPolicy parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static SystemPolicy parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static SystemPolicy parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static SystemPolicy parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static SystemPolicy parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static SystemPolicy parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static SystemPolicy parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static SystemPolicy parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static SystemPolicy parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static SystemPolicy parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static SystemPolicy parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static SystemPolicy parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(SystemPolicy prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code v2ray.core.app.policy.SystemPolicy}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:v2ray.core.app.policy.SystemPolicy)
            com.v2ray.core.app.policy.SystemPolicyOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.v2ray.core.app.policy.ConfigOuterClass.internal_static_v2ray_core_app_policy_SystemPolicy_descriptor;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.v2ray.core.app.policy.ConfigOuterClass.internal_static_v2ray_core_app_policy_SystemPolicy_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            SystemPolicy.class, Builder.class);
        }

        // Construct using com.v2ray.core.app.policy.SystemPolicy.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        @Override
        public Builder clear() {
            super.clear();
            if (statsBuilder_ == null) {
                stats_ = null;
            } else {
                stats_ = null;
                statsBuilder_ = null;
            }
            return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return com.v2ray.core.app.policy.ConfigOuterClass.internal_static_v2ray_core_app_policy_SystemPolicy_descriptor;
        }

        @Override
        public SystemPolicy getDefaultInstanceForType() {
            return SystemPolicy.getDefaultInstance();
        }

        @Override
        public SystemPolicy build() {
            SystemPolicy result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @Override
        public SystemPolicy buildPartial() {
            SystemPolicy result = new SystemPolicy(this);
            if (statsBuilder_ == null) {
                result.stats_ = stats_;
            } else {
                result.stats_ = statsBuilder_.build();
            }
            onBuilt();
            return result;
        }

        @Override
        public Builder clone() {
            return super.clone();
        }

        @Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.setField(field, value);
        }

        @Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.addRepeatedField(field, value);
        }

        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof SystemPolicy) {
                return mergeFrom((SystemPolicy) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(SystemPolicy other) {
            if (other == SystemPolicy.getDefaultInstance()) return this;
            if (other.hasStats()) {
                mergeStats(other.getStats());
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @Override
        public final boolean isInitialized() {
            return true;
        }

        @Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            SystemPolicy parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (SystemPolicy) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private Stats stats_;
        private com.google.protobuf.SingleFieldBuilderV3<
                Stats, Stats.Builder, StatsOrBuilder> statsBuilder_;

        /**
         * <code>.v2ray.core.app.policy.SystemPolicy.Stats stats = 1;</code>
         */
        public boolean hasStats() {
            return statsBuilder_ != null || stats_ != null;
        }

        /**
         * <code>.v2ray.core.app.policy.SystemPolicy.Stats stats = 1;</code>
         */
        public Stats getStats() {
            if (statsBuilder_ == null) {
                return stats_ == null ? Stats.getDefaultInstance() : stats_;
            } else {
                return statsBuilder_.getMessage();
            }
        }

        /**
         * <code>.v2ray.core.app.policy.SystemPolicy.Stats stats = 1;</code>
         */
        public Builder setStats(Stats value) {
            if (statsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                stats_ = value;
                onChanged();
            } else {
                statsBuilder_.setMessage(value);
            }

            return this;
        }

        /**
         * <code>.v2ray.core.app.policy.SystemPolicy.Stats stats = 1;</code>
         */
        public Builder setStats(
                Stats.Builder builderForValue) {
            if (statsBuilder_ == null) {
                stats_ = builderForValue.build();
                onChanged();
            } else {
                statsBuilder_.setMessage(builderForValue.build());
            }

            return this;
        }

        /**
         * <code>.v2ray.core.app.policy.SystemPolicy.Stats stats = 1;</code>
         */
        public Builder mergeStats(Stats value) {
            if (statsBuilder_ == null) {
                if (stats_ != null) {
                    stats_ =
                            Stats.newBuilder(stats_).mergeFrom(value).buildPartial();
                } else {
                    stats_ = value;
                }
                onChanged();
            } else {
                statsBuilder_.mergeFrom(value);
            }

            return this;
        }

        /**
         * <code>.v2ray.core.app.policy.SystemPolicy.Stats stats = 1;</code>
         */
        public Builder clearStats() {
            if (statsBuilder_ == null) {
                stats_ = null;
                onChanged();
            } else {
                stats_ = null;
                statsBuilder_ = null;
            }

            return this;
        }

        /**
         * <code>.v2ray.core.app.policy.SystemPolicy.Stats stats = 1;</code>
         */
        public Stats.Builder getStatsBuilder() {

            onChanged();
            return getStatsFieldBuilder().getBuilder();
        }

        /**
         * <code>.v2ray.core.app.policy.SystemPolicy.Stats stats = 1;</code>
         */
        public StatsOrBuilder getStatsOrBuilder() {
            if (statsBuilder_ != null) {
                return statsBuilder_.getMessageOrBuilder();
            } else {
                return stats_ == null ?
                        Stats.getDefaultInstance() : stats_;
            }
        }

        /**
         * <code>.v2ray.core.app.policy.SystemPolicy.Stats stats = 1;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                Stats, Stats.Builder, StatsOrBuilder>
        getStatsFieldBuilder() {
            if (statsBuilder_ == null) {
                statsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        Stats, Stats.Builder, StatsOrBuilder>(
                        getStats(),
                        getParentForChildren(),
                        isClean());
                stats_ = null;
            }
            return statsBuilder_;
        }

        @Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:v2ray.core.app.policy.SystemPolicy)
    }

    // @@protoc_insertion_point(class_scope:v2ray.core.app.policy.SystemPolicy)
    private static final SystemPolicy DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new SystemPolicy();
    }

    public static SystemPolicy getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SystemPolicy>
            PARSER = new com.google.protobuf.AbstractParser<SystemPolicy>() {
        @Override
        public SystemPolicy parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new SystemPolicy(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<SystemPolicy> parser() {
        return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<SystemPolicy> getParserForType() {
        return PARSER;
    }

    @Override
    public SystemPolicy getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

