// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v2ray.com/core/app/log/config.proto

package com.v2ray.core.app.log;

public interface ConfigOrBuilder extends
        // @@protoc_insertion_point(interface_extends:v2ray.core.app.log.Config)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.v2ray.core.app.log.LogType error_log_type = 1;</code>
     */
    int getErrorLogTypeValue();

    /**
     * <code>.v2ray.core.app.log.LogType error_log_type = 1;</code>
     */
    LogType getErrorLogType();

    /**
     * <code>.v2ray.core.common.log.Severity error_log_level = 2;</code>
     */
    int getErrorLogLevelValue();

    /**
     * <code>.v2ray.core.common.log.Severity error_log_level = 2;</code>
     */
    com.v2ray.core.common.log.Severity getErrorLogLevel();

    /**
     * <code>string error_log_path = 3;</code>
     */
    String getErrorLogPath();

    /**
     * <code>string error_log_path = 3;</code>
     */
    com.google.protobuf.ByteString
    getErrorLogPathBytes();

    /**
     * <code>.v2ray.core.app.log.LogType access_log_type = 4;</code>
     */
    int getAccessLogTypeValue();

    /**
     * <code>.v2ray.core.app.log.LogType access_log_type = 4;</code>
     */
    LogType getAccessLogType();

    /**
     * <code>string access_log_path = 5;</code>
     */
    String getAccessLogPath();

    /**
     * <code>string access_log_path = 5;</code>
     */
    com.google.protobuf.ByteString
    getAccessLogPathBytes();
}
