// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v2ray.com/core/app/dispatcher/config.proto

package com.v2ray.core.app.dispatcher;

public interface SessionConfigOrBuilder extends
        // @@protoc_insertion_point(interface_extends:v2ray.core.app.dispatcher.SessionConfig)
        com.google.protobuf.MessageOrBuilder {
}
