// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v2ray.com/core/transport/internet/kcp/config.proto

package com.v2ray.core.transport.internet.kcp;

public interface ConnectionReuseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:v2ray.core.transport.internet.kcp.ConnectionReuse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool enable = 1;</code>
   */
  boolean getEnable();
}
