// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v2ray.com/core/app/proxyman/command/command.proto

package com.v2ray.core.app.proxyman.command;

public interface RemoveOutboundResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:v2ray.core.app.proxyman.command.RemoveOutboundResponse)
    com.google.protobuf.MessageOrBuilder {
}
